import type { Metadata } from "next"
import Link from "next/link"
import { ChevronLeft, FileText } from "lucide-react"

export const metadata: Metadata = { title: "Terms of Service" }

const sections = [
  {
    title: "Acceptance of terms",
    body: `By accessing or using Haven, you agree to be bound by these Terms of Service. If you do not agree, please do not use the app.`,
  },
  {
    title: "Not a medical service",
    body: `Haven is a wellness and emotional support app. It is NOT a licensed medical service, therapy platform, or crisis intervention service.

The AI Companion (Haven) is not a therapist, counselor, psychologist, or licensed mental health professional. Conversations with Haven are not therapy and should not replace professional mental health care.

If you are experiencing a mental health emergency, please call 988 (Suicide & Crisis Lifeline) or go to your nearest emergency room.`,
  },
  {
    title: "Eligibility",
    body: `You must be at least 13 years old to use Haven. By using the app, you confirm that you meet this requirement. If you are under 18, you should have parental consent.`,
  },
  {
    title: "Your account",
    body: `You are responsible for maintaining the confidentiality of your account credentials. You are responsible for all activity that occurs under your account.

You agree to provide accurate information when creating an account and to keep it up to date. We reserve the right to suspend or terminate accounts that violate these terms.`,
  },
  {
    title: "Acceptable use",
    body: `You agree not to use Haven to:

- Harass, harm, or threaten others
- Upload malicious code or attempt to compromise the security of the service
- Scrape, copy, or redistribute content from the platform without permission
- Use the AI Companion to generate harmful, illegal, or abusive content
- Misrepresent yourself or impersonate others`,
  },
  {
    title: "AI-generated content",
    body: `Responses generated by the Haven AI Companion are produced by Anthropic's Claude model. While we strive to provide thoughtful, supportive responses, AI can make mistakes. Do not rely solely on Haven for important decisions about your health or wellbeing.

Haven is not responsible for decisions made based on AI-generated responses.`,
  },
  {
    title: "Intellectual property",
    body: `The Haven name, logo, design, and content are owned by Haven. You may not reproduce, distribute, or create derivative works without our written permission.

Content you create (journal entries, emotion logs) belongs to you. By storing it in our cloud service, you grant us a limited license to store and display it to you.`,
  },
  {
    title: "Limitation of liability",
    body: `Haven is provided "as is" without warranties of any kind. To the fullest extent permitted by law, Haven shall not be liable for any indirect, incidental, special, or consequential damages arising from your use of the service.

Our total liability to you for any claim shall not exceed the amount you paid us in the past 12 months (which for free users is $0).`,
  },
  {
    title: "Changes to terms",
    body: `We may update these Terms from time to time. We will notify you of material changes by updating the date below or by email. Continued use of Haven after changes constitutes acceptance.`,
  },
  {
    title: "Governing law",
    body: `These Terms are governed by the laws of the United States. Any disputes shall be resolved through binding arbitration or in courts of competent jurisdiction.`,
  },
  {
    title: "Contact",
    body: `Questions about these Terms? Contact us at support@haven.app.`,
  },
]

export default function TermsPage() {
  return (
    <div className="min-h-screen bg-page-gradient">
      <div className="max-w-2xl mx-auto px-4 py-10">

        <Link href="/" className="inline-flex items-center text-muted-foreground hover:text-foreground transition-colors text-sm mb-8">
          <ChevronLeft className="w-4 h-4 mr-1" /> Back
        </Link>

        <div className="flex items-center gap-3 mb-2">
          <div className="w-9 h-9 rounded-xl bg-primary/10 flex items-center justify-center">
            <FileText className="w-4 h-4 text-primary" />
          </div>
          <h1 className="font-serif text-3xl font-semibold text-foreground">Terms of Service</h1>
        </div>
        <p className="text-sm text-muted-foreground mb-10">Last updated: March 2026</p>

        <div className="glass-card rounded-2xl px-6 py-4 mb-8 border border-destructive/20">
          <p className="text-sm font-semibold text-foreground mb-1">Important notice</p>
          <p className="text-sm text-muted-foreground leading-relaxed">
            Haven is a wellness app, not a medical service. It is not a substitute for professional mental health care. If you are in crisis, call or text <a href="tel:988" className="text-primary font-semibold">988</a>.
          </p>
        </div>

        <div className="space-y-6">
          {sections.map(({ title, body }) => (
            <div key={title} className="glass-card rounded-2xl p-6">
              <h2 className="font-semibold text-foreground mb-3">{title}</h2>
              {body.split("\n\n").map((para, i) => (
                <p key={i} className="text-sm text-muted-foreground leading-relaxed mb-3 last:mb-0 whitespace-pre-line">{para}</p>
              ))}
            </div>
          ))}
        </div>

        <p className="text-xs text-muted-foreground text-center mt-10">
          &copy; {new Date().getFullYear()} Haven. All rights reserved.
        </p>
      </div>
    </div>
  )
}
